# Importing Necessary Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings("ignore")

# Importing Dataset

In [3]:
train_data = pd.read_csv("R:\\GUVI\\Tasks\\Task-7\\Glass-KNN\\trainKNN.csv")

In [4]:
test_data = pd.read_csv("R:\\GUVI\\Tasks\\Task-7\\Glass-KNN\\testKNN.csv")

In [5]:
train_data

ID       RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  \
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0   
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0   
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0   
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0   
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0   
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...   
191  207  1.51645  14.94  0.00  1.87  73.11  0.00  8.67  1.38  0.0   
192  208  1.51831  14.39  0.00  1.82  72.86  1.41  6.47  2.88  0.0   
193  209  1.51640  14.37  0.00  2.74  72.85  0.00  9.45  0.54  0.0   
194  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0   
195  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0   

     Type of glass  
0                1  
1                1  
2                1  
3                1  
4                1  
..             ...  
191              7  
192              7  
193              7  
194              7  
195              7  

[196 rows x 11 columns]

In [6]:
test_data

ID       RI     Na    Mg    Al     Si     K     Ca    Ba    Fe  \
0    68  1.52152  13.05  3.65  0.87  72.32  0.19   9.85  0.00  0.17   
1    69  1.52152  13.12  3.58  0.90  72.20  0.23   9.82  0.00  0.16   
2    70  1.52300  13.31  3.58  0.82  71.99  0.12  10.17  0.00  0.03   
3   144  1.51709  13.00  3.47  1.79  72.72  0.66   8.18  0.00  0.00   
4   145  1.51660  12.99  3.18  1.23  72.97  0.58   8.81  0.00  0.24   
5   146  1.51839  12.85  3.67  1.24  72.57  0.62   8.68  0.00  0.35   
6   161  1.51832  13.33  3.34  1.54  72.14  0.56   8.99  0.00  0.00   
7   162  1.51934  13.64  3.54  0.75  72.65  0.16   8.89  0.15  0.24   
8   163  1.52211  14.19  3.78  0.91  71.36  0.23   9.14  0.00  0.37   
9   174  1.52043  13.38  0.00  1.40  72.25  0.33  12.50  0.00  0.00   
10  175  1.52058  12.85  1.61  2.17  72.18  0.76   9.70  0.24  0.51   
11  176  1.52119  12.97  0.33  1.51  73.39  0.13  11.27  0.00  0.28   
12  183  1.51916  14.15  0.00  2.09  72.74  0.00  10.88  0.00  0.00   
13  184  1.51969  14.56  0.00  0.56  73.48  0.00  11.22  0.00  0.00   
14  185  1.51115  17.38  0.00  0.34  75.41  0.00   6.65  0.00  0.00   
15  212  1.52065  14.36  0.00  2.02  73.42  0.00   8.44  1.64  0.00   
16  213  1.51651  14.38  0.00  1.94  73.61  0.00   8.48  1.57  0.00   
17  214  1.51711  14.23  0.00  2.08  73.36  0.00   8.62  1.67  0.00   

    Type of glass  
0               1  
1               1  
2               1  
3               2  
4               2  
5               2  
6               3  
7               3  
8               3  
9               5  
10              5  
11              5  
12              6  
13              6  
14              6  
15              7  
16              7  
17              7

# Data Preprocessing

In [7]:
train_data.isnull().sum()

ID               0
RI               0
Na               0
Mg               0
Al               0
Si               0
K                0
Ca               0
Ba               0
Fe               0
Type of glass    0
dtype: int64

In [8]:
train_data.dtypes

ID                 int64
RI               float64
Na               float64
Mg               float64
Al               float64
Si               float64
K                float64
Ca               float64
Ba               float64
Fe               float64
Type of glass      int64
dtype: object

In [9]:
train_data.describe()

ID          RI          Na          Mg          Al          Si  \
count  196.000000  196.000000  196.000000  196.000000  196.000000  196.000000   
mean   102.862245    1.518295   13.375204    2.758980    1.454337   72.635408   
std     61.195663    0.003055    0.783145    1.392641    0.491688    0.763578   
min      1.000000    1.511310   10.730000    0.000000    0.290000   69.810000   
25%     49.750000    1.516458   12.877500    2.362500    1.190000   72.317500   
50%    101.500000    1.517630   13.280000    3.480000    1.360000   72.810000   
75%    153.250000    1.518985   13.792500    3.610000    1.622500   73.080000   
max    211.000000    1.533930   15.790000    4.490000    3.500000   75.180000   

                K          Ca          Ba          Fe  Type of glass  
count  196.000000  196.000000  196.000000  196.000000     196.000000  
mean     0.519388    8.910714    0.164235    0.050255       2.668367  
std      0.672703    1.421490    0.485198    0.086359       2.062416  
min      0.000000    5.430000    0.000000    0.000000       1.000000  
25%      0.140000    8.220000    0.000000    0.000000       1.000000  
50%      0.560000    8.575000    0.000000    0.000000       2.000000  
75%      0.610000    9.092500    0.000000    0.090000       3.000000  
max      6.210000   16.190000    3.150000    0.340000       7.000000

In [10]:
IQR = train_data.Al.quantile(0.75) - train_data.Al.quantile(0.25)
UL = train_data.Al.quantile(0.75) + 1.5*IQR
LL = train_data.Al.quantile(0.25) - 1.5*IQR
UL,LL

(2.27125, 0.5412499999999998)

In [11]:
IQR = train_data.K.quantile(0.75) - train_data.K.quantile(0.25)
UL = train_data.K.quantile(0.75) + 1.5*IQR
LL = train_data.K.quantile(0.25) - 1.5*IQR
UL,LL

(1.315, -0.565)

In [12]:
IQR = train_data.Ca.quantile(0.75) - train_data.Ca.quantile(0.25)
UL = train_data.Ca.quantile(0.75) + 1.5*IQR
LL = train_data.Ca.quantile(0.25) - 1.5*IQR
UL,LL

(10.401250000000001, 6.91125)

In [13]:
IQR = train_data.Fe.quantile(0.75) - train_data.Fe.quantile(0.25)
UL = train_data.Fe.quantile(0.75) + 1.5*IQR
LL = train_data.Fe.quantile(0.25) - 1.5*IQR
UL,LL

(0.225, -0.135)

In [14]:
train_data.describe()

ID          RI          Na          Mg          Al          Si  \
count  196.000000  196.000000  196.000000  196.000000  196.000000  196.000000   
mean   102.862245    1.518295   13.375204    2.758980    1.454337   72.635408   
std     61.195663    0.003055    0.783145    1.392641    0.491688    0.763578   
min      1.000000    1.511310   10.730000    0.000000    0.290000   69.810000   
25%     49.750000    1.516458   12.877500    2.362500    1.190000   72.317500   
50%    101.500000    1.517630   13.280000    3.480000    1.360000   72.810000   
75%    153.250000    1.518985   13.792500    3.610000    1.622500   73.080000   
max    211.000000    1.533930   15.790000    4.490000    3.500000   75.180000   

                K          Ca          Ba          Fe  Type of glass  
count  196.000000  196.000000  196.000000  196.000000     196.000000  
mean     0.519388    8.910714    0.164235    0.050255       2.668367  
std      0.672703    1.421490    0.485198    0.086359       2.062416  
min      0.000000    5.430000    0.000000    0.000000       1.000000  
25%      0.140000    8.220000    0.000000    0.000000       1.000000  
50%      0.560000    8.575000    0.000000    0.000000       2.000000  
75%      0.610000    9.092500    0.000000    0.090000       3.000000  
max      6.210000   16.190000    3.150000    0.340000       7.000000

In [15]:
train_data = train_data.drop_duplicates()
train_data.shape

(196, 11)

In [16]:
train_data = train_data.drop("ID",axis=1)
test_data = test_data.drop("ID",axis=1)

# Train Test Dataset

In [17]:
x_train = train_data.loc[:,["RI","Na","Mg","Al","Si","K","Ca","Ba","Fe"]].values
y_train = train_data.loc[:,"Type of glass"].values
x_test = test_data.loc[:,["RI","Na","Mg","Al","Si","K","Ca","Ba","Fe"]].values
y_test = test_data.loc[:,"Type of glass"].values

In [18]:
x_train

array([[ 1.52101, 13.64   ,  4.49   , ...,  8.75   ,  0.     ,  0.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  7.83   ,  0.     ,  0.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  7.78   ,  0.     ,  0.     ],
       ...,
       [ 1.5164 , 14.37   ,  0.     , ...,  9.45   ,  0.54   ,  0.     ],
       [ 1.51623, 14.14   ,  0.     , ...,  9.18   ,  1.06   ,  0.     ],
       [ 1.51685, 14.92   ,  0.     , ...,  8.4    ,  1.59   ,  0.     ]])

In [19]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
      dtype=int64)

In [20]:
x_test

array([[1.52152e+00, 1.30500e+01, 3.65000e+00, 8.70000e-01, 7.23200e+01,
        1.90000e-01, 9.85000e+00, 0.00000e+00, 1.70000e-01],
       [1.52152e+00, 1.31200e+01, 3.58000e+00, 9.00000e-01, 7.22000e+01,
        2.30000e-01, 9.82000e+00, 0.00000e+00, 1.60000e-01],
       [1.52300e+00, 1.33100e+01, 3.58000e+00, 8.20000e-01, 7.19900e+01,
        1.20000e-01, 1.01700e+01, 0.00000e+00, 3.00000e-02],
       [1.51709e+00, 1.30000e+01, 3.47000e+00, 1.79000e+00, 7.27200e+01,
        6.60000e-01, 8.18000e+00, 0.00000e+00, 0.00000e+00],
       [1.51660e+00, 1.29900e+01, 3.18000e+00, 1.23000e+00, 7.29700e+01,
        5.80000e-01, 8.81000e+00, 0.00000e+00, 2.40000e-01],
       [1.51839e+00, 1.28500e+01, 3.67000e+00, 1.24000e+00, 7.25700e+01,
        6.20000e-01, 8.68000e+00, 0.00000e+00, 3.50000e-01],
       [1.51832e+00, 1.33300e+01, 3.34000e+00, 1.54000e+00, 7.21400e+01,
        5.60000e-01, 8.99000e+00, 0.00000e+00, 0.00000e+00],
       [1.51934e+00, 1.36400e+01, 3.54000e+00, 7.50000e-01, 7.

In [21]:
y_test

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 5, 5, 5, 6, 6, 6, 7, 7, 7], dtype=int64)

# Scaling of Dataset

In [22]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [23]:
x_train_scaled

array([[ 0.89081203,  0.3389847 ,  1.24616006, ..., -0.11334995,
        -0.33935667, -0.5834224 ],
       [-0.22479561,  0.65902807,  0.60544985, ..., -0.76221546,
        -0.33935667, -0.5834224 ],
       [-0.69400706,  0.19816562,  0.56945489, ..., -0.79747989,
        -0.33935667, -0.5834224 ],
       ...,
       [-0.62182068,  1.27351132, -1.98618697, ...,  0.38035207,
         0.77644048, -0.5834224 ],
       [-0.67760106,  0.97907143, -1.98618697, ...,  0.18992414,
         1.8509118 , -0.5834224 ],
       [-0.47416673,  1.97760672, -1.98618697, ..., -0.36020096,
         2.94604604, -0.5834224 ]])

In [24]:
x_test_scaled

array([[ 1.05815318, -0.41631763,  0.6414448 , -1.19147352, -0.41412376,
        -0.49090172,  0.66246751, -0.33935667,  1.39014453],
       [ 1.05815318, -0.32670549,  0.59105186, -1.13030296, -0.57168104,
        -0.43128788,  0.64130885, -0.33935667,  1.27405236],
       [ 1.54377062, -0.08347253,  0.59105186, -1.29342446, -0.84740628,
        -0.59522593,  0.88815986, -0.33935667, -0.23514588],
       [-0.39541795, -0.4803263 ,  0.51186296,  0.68442367,  0.11106716,
         0.20956089, -0.51536445, -0.33935667, -0.5834224 ],
       [-0.5561967 , -0.49312804,  0.30309222, -0.4574268 ,  0.43931149,
         0.09033322, -0.07103264, -0.33935667,  2.20278974],
       [ 0.03113791, -0.67235232,  0.65584279, -0.43703661, -0.08587943,
         0.14994705, -0.16272016, -0.33935667,  3.47980364],
       [ 0.00816952, -0.05786907,  0.41827608,  0.174669  , -0.65045968,
         0.0605263 ,  0.05591931, -0.33935667, -0.5834224 ],
       [ 0.34285181,  0.3389847 ,  0.5622559 , -1.43615577,  0

# Hyperparameter Tuning

In [25]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
for k in [1,2,3,4,5,6,7,8,9,10,20,30,40,50,60]:
    KNN = KNeighborsClassifier(n_neighbors=k) 
    KNN.fit(x_train_scaled, y_train)
    print("K-Value:",k, " Accuracy : ",KNN.score(x_train_scaled,y_train), "CV Score : ",np.mean(cross_val_score(KNN, x_train_scaled, y_train, cv=10)))

K-Value: 1  Accuracy :  1.0 CV Score :  0.6678947368421053
K-Value: 2  Accuracy :  0.8418367346938775 CV Score :  0.7194736842105264
K-Value: 3  Accuracy :  0.8520408163265306 CV Score :  0.6834210526315789
K-Value: 4  Accuracy :  0.7959183673469388 CV Score :  0.6892105263157895
K-Value: 5  Accuracy :  0.8010204081632653 CV Score :  0.6786842105263158
K-Value: 6  Accuracy :  0.7806122448979592 CV Score :  0.6786842105263158
K-Value: 7  Accuracy :  0.7346938775510204 CV Score :  0.653157894736842
K-Value: 8  Accuracy :  0.7551020408163265 CV Score :  0.6634210526315789
K-Value: 9  Accuracy :  0.7244897959183674 CV Score :  0.6526315789473685
K-Value: 10  Accuracy :  0.7142857142857143 CV Score :  0.6581578947368422
K-Value: 20  Accuracy :  0.6938775510204082 CV Score :  0.5813157894736843
K-Value: 30  Accuracy :  0.6428571428571429 CV Score :  0.5865789473684211
K-Value: 40  Accuracy :  0.6173469387755102 CV Score :  0.5810526315789474
K-Value: 50  Accuracy :  0.6224489795918368 CV Sco

# KNN Model using Euclidean Distance Metric

In [26]:
KNN = KNeighborsClassifier(n_neighbors=2) 
KNN.fit(x_train_scaled, y_train)
KNN.score(x_test_scaled, y_test)

0.4444444444444444

In [27]:
y_pred = KNN.predict(x_test_scaled)

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3, 0, 0, 0, 0, 0],
       [2, 1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [1, 2, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 3]], dtype=int64)

In [29]:
from sklearn.metrics import roc_auc_score
predict_proba = KNN.predict_proba(x_test_scaled)
roc_auc_score(y_test, predict_proba, multi_class="ovo")

0.8074074074074074

# KNN Model using Manhattan Distance Metric

In [30]:
KNN_M = KNeighborsClassifier(n_neighbors=2, metric="manhattan") 
KNN_M.fit(x_train_scaled, y_train)
KNN_M.score(x_test_scaled, y_test)

0.4444444444444444

In [31]:
predict_proba_M = KNN_M.predict_proba(x_test_scaled)

In [32]:
y_pred_M = KNN_M.predict(x_test_scaled)

In [33]:
confusion_matrix(y_test, y_pred_M)

array([[3, 0, 0, 0, 0, 0],
       [2, 1, 0, 0, 0, 0],
       [2, 1, 0, 0, 0, 0],
       [0, 2, 0, 1, 0, 0],
       [0, 2, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 3]], dtype=int64)

In [34]:
roc_auc_score(y_test, predict_proba_M, multi_class="ovr")

0.8462962962962962

# Scikit Classification Report 

In [35]:
from sklearn.metrics import classification_report
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           1       0.50      1.00      0.67         3
           2       0.14      0.33      0.20         3
           3       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         3
           6       1.00      0.33      0.50         3
           7       1.00      1.00      1.00         3

    accuracy                           0.44        18
   macro avg       0.44      0.44      0.39        18
weighted avg       0.44      0.44      0.39        18



In [36]:
from sklearn.metrics import classification_report
report_M = classification_report(y_test,y_pred_M)
print(report_M)

              precision    recall  f1-score   support

           1       0.43      1.00      0.60         3
           2       0.17      0.33      0.22         3
           3       0.00      0.00      0.00         3
           5       0.50      0.33      0.40         3
           6       0.00      0.00      0.00         3
           7       1.00      1.00      1.00         3

    accuracy                           0.44        18
   macro avg       0.35      0.44      0.37        18
weighted avg       0.35      0.44      0.37        18

